######################################################################
# Automatically generated by qmake (2.01a) Fr 10. Dez 22:55:42 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Farn.h
SOURCES += Farn.cpp main.cpp
RC_FILE += res.rc
RESOURCES += resources.qrc